# Generated by Django 2.2.1 on 2019-05-07 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortalidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
        migrations.AlterModelTable(
            name='mortality',
            table='mortality',
        ),
    ]
